version: '3.1'

services:
  db:
    container_name : postgres
    image: postgres
    restart: unless-stopped
    env_file : .env
  backend:
    container_name : backend
    image: backend:trs
    build : ./services/backend/
    restart: unless-stopped
    env_file : .env
    ports:
      - "8000:8000"
    depends_on:
      - db
  frontend:
    container_name : frontend
    image: frontend:trs
    build : ./services/frontend/
    volumes:
      - ./services/frontend/src/:/app/src # Mount the source code
    restart: unless-stopped
    env_file : .env
    ports:
      - "5173:5173"
    depends_on:
      - db

networks:
  trs:
    name : trs
    driver: bridge
