version: '3.8'

services:
  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
  web:
    build: .
    env_file:
      - .env
    command: ./start_django.sh
    volumes:
      - ./src:/code/src
    ports:
      - "8000:8000"
    depends_on:
      - db
  redis:
    image: "redis:alpine"
    ports:
      - "7474:6379"

volumes:
  postgres_data:
    driver: local